city_to_id = {
    "Chau Doc": "VN44",
    "Vung Tau": "VN43",
    "Bac Giang": "VN54",
    "Bac Can": "VN53",
    "Bac Lieu": "VN55",
    "Bac Ninh": "VN56",
    "Ben Tre": "VN50",
    "Qui Nhon": "VN31",
    "Xom Ong Ho": "VN57", 
    "Tay Ninh": "VN58",
    "Phan Thiet": "VN40",
    "Ca Mau": "VN59",
    "Can Tho": "VNCT",
    "Cao Bang": "VN04",
    "Atba Village": "VNDN", 
    "Buon Me Thuot": "VN33",
    "Tu Xoay": "VN72",
    "Dien Bien": "VN71",
    "Dong Xoai": "VN58",
    "Bien Hoa": "VN39",
    "Play Cu": "VN30",
    "Ha Giang": "VN03",
    "Phu Ly": "VN63",
    "Ha Noi": "VNHN",
    "Ha Tinh": "VN23",
    "Hai Duong": "VN61",
    "Hai Phong": "VNHP",
    "Ap Tan Qui Kinh": "VN73", 
    "Ho Chi Minh City": "VNSG",
    "Hoa Binh": "VN14",
    "Hong-Yen": "VN66", 
    "Ninh Quang": "VN34",  
    "Rach Gia": "VN47",
    "Kon Tum": "VN28",
    "Pa Nhie": "VN01", 
    "Da Lat": "VN35",
    "Lang Son": "VN09",
    "Lao Cai": "VN02",
    "Tan An": "VN41",
    "Nam Dinh": "VN67",
    "Vinh": "VN22",
    "Ninh Binh": "VN18",
    "Thon Suoi La": "VN36",
    "Thanh Loi": "VN45",
    "Viet Tri": "VN68",
    "Xuan Loc Ha": "VN32",
    "Dong Hoi": "VN24",
    "Hoi An": "VN27",
    "Quang Ngai": "VN29",
    "Cam Pha": "VN13",
    "Thon Nhu Le": "VN25",
    "Soc Trang": "VN52",
    "Son La": "VN05",
    "Tay Ninh": "VN37",
    "Thai Binh": "VN20",
    "Thai Nguyen": "VN69",
    "Thanh Hoa": "VN21",
    "Thua Thien Hue": "VN26",
    "My Tho": "VN46",  
    "Tra Vinh": "VN51",
    "Tuyen Quang": "VN07",
    "Vinh Long": "VN49",
    "Vinh Yen": "VN70",  
    "Yen Bai": "VN06"
}
city_to_province = {
    "Chau Doc": "An Giang",
    "Vung Tau": "Bà Rịa-Vũng Tàu",
    "Bac Giang": "Bắc Giang",
    "Bac Can": "Bắc Kạn",
    "Bac Lieu": "Bạc Liêu",
    "Bac Ninh": "Bắc Ninh",
    "Ben Tre": "Bến Tre",
    "Qui Nhon": "Bình Định",
    "Xom Ong Ho": "Bình Dương",
    "Dong Xoai": "Bình Phước",
    "Phan Thiet": "Bình Thuận",
    "Ca Mau": "Cà Mau",
    "Can Tho": "Cần Thơ",
    "Cao Bang": "Cao Bằng",
    "Atba Village": "Đà Nẵng",
    "Buon Me Thuot": "Đắk Lắk",
    "Tu Xoay": "Đắk Nông",
    "Dien Bien": "Điện Biên",
    "Bien Hoa": "Đồng Nai",
    "Thanh Loi": "Đồng Tháp",
    "Play Cu": "Gia Lai",
    "Ha Giang": "Hà Giang",
    "Phu Ly": "Hà Nam",
    "Ha Noi": "Hà Nội",
    "Ha Tinh": "Hà Tĩnh",
    "Hai Duong": "Hải Dương",
    "Hai Phong": "Hải Phòng",
    "Ap Tan Qui Kinh": "Hậu Giang",
    "Ho Chi Minh City": "TP. Hồ Chí Minh",
    "Hoa Binh": "Hòa Bình",
    "Hong-Yen": "Hưng Yên",
    "Ninh Quang": "Khánh Hòa",
    "Rach Gia": "Kiên Giang",
    "Kon Tum": "Kon Tum",
    "Pa Nhie": "Lai Châu",
    "Da Lat": "Lâm Đồng",
    "Lang Son": "Lạng Sơn",
    "Lao Cai": "Lào Cai",
    "Tan An": "Long An",
    "Nam Dinh": "Nam Định",
    "Vinh": "Nghệ An",
    "Ninh Binh": "Ninh Bình",
    "Thon Suoi La": "Ninh Thuận",
    "Viet Tri": "Phú Thọ",
    "Xuan Loc Ha": "Phú Yên",
    "Dong Hoi": "Quảng Bình",
    "Hoi An": "Quảng Nam",
    "Quang Ngai": "Quảng Ngãi",
    "Cam Pha": "Quảng Ninh",
    "Thon Nhu Le": "Quảng Trị",
    "Soc Trang": "Sóc Trăng",
    "Son La": "Sơn La",
    "Tay Ninh": "Tây Ninh",
    "Thai Binh": "Thái Bình",
    "Thai Nguyen": "Thái Nguyên",
    "Thanh Hoa": "Thanh Hóa",
    "Thua Thien Hue": "Thừa Thiên - Huế",
    "My Tho": "Tiền Giang",
    "Tra Vinh": "Trà Vinh",
    "Tuyen Quang": "Tuyên Quang",
    "Vinh Long": "Vĩnh Long",
    "Vinh Yen": "Vĩnh Phúc",
    "Yen Bai": "Yên Bái"
}