city_to_id = {
    "Chau Doc": "VN44",
    "Vung Tau": "VN43",
    "Bac Giang": "VN54",
    "Bac Can": "VN53",
    "Bac Lieu": "VN55",
    "Bac Ninh": "VN56",
    "Ben Tre": "VN50",
    "Qui Nhon": "VN31",
    "Xom Ong Ho": "VN57", 
    "Tay Ninh": "VN58",
    "Phan Thiet": "VN40",
    "Ca Mau": "VN59",
    "Can Tho": "VNCT",
    "Cao Bang": "VN04",
    "Atba Village": "VNDN", 
    "Buon Me Thuot": "VN33",
    "Tu Xoay": "VN72",
    "Dien Bien": "VN71",
    "Dong Xoai": "VN58",
    "Bien Hoa": "VN39",
    "Play Cu": "VN30",
    "Ha Giang": "VN03",
    "Phu Ly": "VN63",
    "Ha Noi": "VNHN",
    "Ha Tinh": "VN23",
    "Hai Duong": "VN61",
    "Hai Phong": "VNHP",
    "Ap Tan Qui Kinh": "VN73", 
    "Ho Chi Minh City": "VNSG",
    "Hoa Binh": "VN14",
    "Hong-Yen": "VN66", 
    "Ninh Quang": "VN34",  
    "Rach Gia": "VN47",
    "Kon Tum": "VN28",
    "Pa Nhie": "VN01", 
    "Da Lat": "VN35",
    "Lang Son": "VN09",
    "Lao Cai": "VN02",
    "Tan An": "VN41",
    "Nam Dinh": "VN67",
    "Vinh": "VN22",
    "Ninh Binh": "VN18",
    "Thon Suoi La": "VN36",
    "Thanh Loi": "VN45",
    "Viet Tri": "VN68",
    "Xuan Loc Ha": "VN32",
    "Dong Hoi": "VN24",
    "Hoi An": "VN27",
    "Quang Ngai": "VN29",
    "Cam Pha": "VN13",
    "Thon Nhu Le": "VN25",
    "Soc Trang": "VN52",
    "Son La": "VN05",
    "Tay Ninh": "VN37",
    "Thai Binh": "VN20",
    "Thai Nguyen": "VN69",
    "Thanh Hoa": "VN21",
    "Thua Thien Hue": "VN26",
    "My Tho": "VN46",  
    "Tra Vinh": "VN51",
    "Tuyen Quang": "VN07",
    "Vinh Long": "VN49",
    "Vinh Yen": "VN70",  
    "Yen Bai": "VN06"
}
